"use strict";

// Match flight number with airlines
// install the airline logo images in airlines-tiny folder.
// list based on IATA https://www.iata.org/about/members/Pages/airline-list.aspx?All=true

var AirlinesDatabase = {
	"AAF": { name: "Aigle Azur", image: "AAF.png" },
	"AAL": { name: "American Airlines", image: "AAL.png" },
	"AAR": { name: "Asiana Airlines", image: "AAR.png" },
	"AAY": { name: "Allegiant Air", image: "AAY.png" },
	"ABL": { name: "Air Busan", image: "ABL.png" },
	"ABW": { name: "AirBridgeCargo Airlines", image: "ABW.png" },
	"ABY": { name: "Air Arabia", image: "ABY.png" },
	"ACA": { name: "Air Canada", image: "ACA.png" },
	"ACI": { name: "Aircalin", image: "ACI.png" },
	"ADR": { name: "Adria Airways", image: "ADR.png" },
	"AEA": { name: "Air Europa", image: "AEA.png" },
	"AEE": { name: "Aegean Airlines", image: "AEE.png" },
	"AFL": { name: "Aeroflot", image: "AFL.png" },
	"AFR": { name: "Air France", image: "AFR.png" },
	"AFW": { name: "Africa World Airlines", image: "AFW.png" },
	//"AHY": { name: "Azerbaijan Airlines", image: "AHY.png" },
	"AIC": { name: "Air India", image: "AIC.png" },
	"AIJ": { name: "Interjet", image: "AIJ.png" },
	//"AIZ": { name: "Arkia Israeli Airlines", image: "AIZ.png" },
	//"AJK": { name: "Allied Air", image: "AJK.png" },
	//"ALK": { name: "SriLankan Airlines", image: "ALK.png" },
	//"AMC": { name: "Air Malta", image: "AMC.png" },
	"AMU": { name: "Air Macau", image: "AMU.png" },
	"AMX": { name: "Aeromexico", image: "AMX.png" },
	"ANA": { name: "ANA", image: "ANA.png" },
	//"ANE": { name: "Air Nostrum", image: "ANE.png" },
	//"ANG": { name: "Air Niugini", image: "ANG.png" },
	"ANZ": { name: "Air New Zealand", image: "ANZ.png" },
	"APJ": { name: "Peach Aviation", image: "APJ.png" },
	//"APK": { name: "Air Peace", image: "APK.png" },
	//"ARA": { name: "Arik Air", image: "ARA.png" },
	"ARE": { name: "LATAM Airlines Colombia", image: "ARE.png" },
	"ARG": { name: "Aerolineas Argentinas", image: "ARG.png" },
	"ASA": { name: "Alaska Airlines", image: "ASA.png" },
	"ASL": { name: "Air Serbia", image: "ASL.png" },
	"AUA": { name: "Austrian", image: "AUA.png" },
	//"AUI": { name: "Ukraine International Airlines", image: "AUI.png" },
	//"AUL": { name: "Nordavia Regional Airlines", image: "AUL.png" },
	//"AUT": { name: "Austral", image: "AUT.png" },
	"AVA": { name: "Avianca", image: "AVA.png" },
	//"AVN": { name: "Air Vanuatu", image: "AVN.png" },
	"AXM": { name: "AirAsia", image: "AXM.png" },
	"AZA": { name: "Alitalia", image: "AZA.png" },
	//"AZG": { name: "Silk Way West Airlines", image: "AZG.png" },
	"AZU": { name: "Azul Brazilian Airlines", image: "AZU.png" },
	"BAW": { name: "British Airways", image: "BAW.png" },
	//"BBC": { name: "Biman Bangladesh Airlines", image: "BBC.png" },
	//"BCS": { name: "European Air Transport", image: "BCS.png" },
	"BCY": { name: "CityJet", image: "BCY.png" },
	//"BEE": { name: "flybe", image: "BEE.png" },
	"BEL": { name: "Brussels Airlines", image: "BEL.png" },
	//"BGH": { name: "BH Air", image: "BGH.png" },
	//"BHS": { name: "Bahamasair", image: "BHS.png" },
	"BKP": { name: "Bangkok Airways", image: "BKP.png" },
	//"BMR": { name: "bmi Regional", image: "BMR.png" },
	//"BMS": { name: "Blue Air", image: "BMS.png" },
	//"BOT": { name: "Air Botswana", image: "BOT.png" },
	//"BOV": { name: "BoA Boliviana de Aviacion", image: "BOV.png" },
	//"BPA": { name: "Blue Panorama", image: "BPA.png" },
	//"BRU": { name: "Belavia Belarusian Airlines", image: "BRU.png" },
	//"BTI": { name: "Air Baltic", image: "BTI.png" },
	//"BTK": { name: "Batik Air", image: "BTK.png" },
	"BWA": { name: "Caribbean Airlines", image: "BWA.png" },
	//"CAI": { name: "Corendon Airlines", image: "CAI.png" },
	"CAL": { name: "China Airlines", image: "CAL.png" },
	//"CAW": { name: "Comair", image: "CAW.png" },
	//"CAY": { name: "Cayman Airways", image: "CAY.png" },
	//"CBG": { name: "GX Airlines", image: "CBG.png" },
	//"CBJ": { name: "Capital Airlines", image: "CBJ.png" },
	"CCA": { name: "Air China", image: "CCA.png" },
	//"CCM": { name: "Air Corsica", image: "CCM.png" },
	//"CDC": { name: "Loong Air", image: "CDC.png" },
	"CDG": { name: "Shandong Airlines", image: "CDG.png" },
	"CEB": { name: "Cebu Pacific", image: "CEB.png" },
	"CES": { name: "China Eastern", image: "CES.png" },
	//"CFG": { name: "Condor", image: "CFG.png" },
	//"CGA": { name: "Congo Airways", image: "CGA.png" },
	"CHH": { name: "Hainan Airlines", image: "CHH.png" },
	//"CJT": { name: "Cargojet Airways", image: "CJT.png" },
	//"CKK": { name: "China Cargo Airlines", image: "CKK.png" },
	//"CLH": { name: "Lufthansa CityLine", image: "CLH.png" },
	"CLX": { name: "Cargolux", image: "CLX.png" },
	"CMP": { name: "COPA Airlines", image: "CMP.png" },
	"CPA": { name: "Cathay Pacific", image: "CPA.png" },
	//"CRC": { name: "Camair-Co", image: "CRC.png" },
	"CRK": { name: "Hong Kong Airlines", image: "CRK.png" },
	//"CRL": { name: "Corsair International", image: "CRL.png" },
	"CSA": { name: "Czech Airlines", image: "CSA.png" },
	"CSC": { name: "Sichuan Airlines", image: "CSC.png" },
	"CSH": { name: "Shanghai Airlines", image: "CSH.png" },
	"CSN": { name: "China Southern Airlines", image: "CSN.png" },
	//"CSS": { name: "SF Airlines", image: "CSS.png" },
	"CSZ": { name: "Shenzhen Airlines", image: "CSZ.png" },
	"CTN": { name: "Croatia Airlines", image: "CTN.png" },
	//"CUB": { name: "Cubana", image: "CUB.png" },
	//"CUH": { name: "Urumqi Air", image: "CUH.png" },
	"CXA": { name: "Xiamen Airlines", image: "CXA.png" },
	"CYP": { name: "Cyprus Airways", image: "CYP.png" },
	//"CYZ": { name: "China Postal Airlines", image: "CYZ.png" },
	//"DAH": { name: "Air Algérie", image: "DAH.png" },
	"DAL": { name: "Delta Air Lines", image: "DAL.png" },
	"DHK": { name: "DHL Air", image: "DHK.png" },
	"DHX": { name: "DHL Aviation", image: "DHX.png" },
	//"DKH": { name: "Juneyao Airlines", image: "DKH.png" },
	//"DLA": { name: "Air Dolomiti", image: "DLA.png" },
	"DLH": { name: "Lufthansa", image: "DLH.png" },
	//"DSM": { name: "LATAM Airlines Argentina", image: "DSM.png" },
	//"DTA": { name: "TAAG Angola Airlines", image: "DTA.png" },
	//"DTH": { name: "Tassili Airlines", image: "DTH.png" },
	//"EIN": { name: "Aer Lingus", image: "EIN.png" },
	//"ELY": { name: "EL AL", image: "ELY.png" },
	//"ERH": { name: "Ravn Alaska", image: "ERH.png" },
	"ESR": { name: "Eastar Jet", image: "ESR.png" },
	"ETD": { name: "Etihad Airways", image: "ETD.png" },
	"ETH": { name: "Ethiopian Airlines", image: "ETH.png" },
	"EVA": { name: "EVA Air", image: "EVA.png" },
	//"EVE": { name: "Evelop Airlines", image: "EVE.png" },
	"EZY": { name: "EasyJet", image: "EZY.png" },
	"EWG": { name: "Eurowings", image: "EWG.png" },
	//"EXY": { name: "South African Express Airways", image: "EXY.png" },
	"FDB": { name: "flydubai", image: "FDB.png" },
	"FDX": { name: "FedEx Express", image: "FDX.png" },
	"FEA": { name: "Far Eastern Air Transport", image: "FEA.png" },
	"FEG": { name: "FlyEgypt", image: "FEG.png" },
	"FFT": { name: "Frontier Airlines", image: "FFT.png" },
	//"FHY": { name: "Freebird Airlines", image: "FHY.png" },
	"FIN": { name: "Finnair", image: "FIN.png" },
	"FJI": { name: "Fiji Airways", image: "FJI.png" },
	"FLI": { name: "Atlantic Airways", image: "FLI.png" },
	//"FWI": { name: "Air Caraibes", image: "FWI.png" },
	"FZA": { name: "Fuzhou Airlines", image: "FZA.png" },
	"GCR": { name: "Tianjin Airlines", image: "GCR.png" },
	"GEC": { name: "Lufthansa Cargo", image: "GEC.png" },
	//"GFA": { name: "Gulf Air", image: "GFA.png" },
	//"GIA": { name: "Garuda Indonesia", image: "GIA.png" },
	//"GLG": { name: "Avianca Ecuador", image: "GLG.png" },
	//"GLO": { name: "GOL Linhas Aereas", image: "GLO.png" },
	//"GMI": { name: "Germania", image: "GMI.png" },
	//"GSW": { name: "Germania Flug AG", image: "GSW.png" },
	//"GTI": { name: "Atlas Air", image: "GTI.png" },
	"HAL": { name: "Hawaiian Airlines", image: "HAL.png" },
	//"HBH": { name: "Hebei Airlines", image: "HBH.png" },
	"HDA": { name: "Cathay Dragon", image: "HDA.png" },
	//"HFY": { name: "Hi Fly", image: "HFY.png" },
	//"HHN": { name: "Hahn Air", image: "HHN.png" },
	//"HKC": { name: "Hong Kong Air Cargo", image: "HKC.png" },
	"HKE": { name: "HK Express", image: "HKE.png" },
	"HVN": { name: "Vietnam Airlines", image: "HVN.png" },
	//"HXA": { name: "China Express Airlines", image: "HXA.png" },
	//"IBB": { name: "Binter Canarias", image: "IBB.png" },
	"IBE": { name: "IBERIA", image: "IBE.png" },
	"ICE": { name: "Icelandair", image: "ICE.png" },
	//"ICL": { name: "CAL Cargo Airlines", image: "ICL.png" },
	//"IRA": { name: "Iran Air", image: "IRA.png" },
	//"IRB": { name: "Iran Airtour Airline", image: "IRB.png" },
	//"IRC": { name: "Iran Aseman Airlines", image: "IRC.png" },
	//"IRK": { name: "Kish Air", image: "IRK.png" },
	//"IRM": { name: "Mahan Air", image: "IRM.png" },
	//"ISR": { name: "Israir", image: "ISR.png" },
	"ISS": { name: "Air Italy", image: "ISS.png" },
	"JAI": { name: "Jet Airways", image: "JAI.png" },
	"JAL": { name: "Japan Airlines", image: "JAL.png" },
	"JAV": { name: "Jordan Aviation", image: "JAV.png" },
	"JBU": { name: "JetBlue", image: "JBU.png" },
	"JJA": { name: "Jeju Air", image: "JJA.png" },
	"JJP": { name: "Jetstar Japan" , image: "JJP.png" },
	//"JLL": { name: "Jet Lite (India)", image: "JLL.png" },
	"JNA": { name: "Jin Air", image: "JNA.png" },
	"JSA": { name: "Jetstar Asia Airways", image: "JSA.png" },
	"JST": { name: "Jetstar Airways", image: "JST.png" },
	//"JZR": { name: "Jazeera Airways", image: "JZR.png" },
	//"KAC": { name: "Kuwait Airways", image: "KAC.png" },
	"KAL": { name: "Korean Air", image: "KAL.png" },
	//"KAR": { name: "Pegas Fly", image: "KAR.png" },
	//"KEM": { name: "Cemair", image: "KEM.png" },
	//"KHV": { name: "Cambodia Angkor Air", image: "KHV.png" },
	//"KKK": { name: "AtlasGlobal", image: "KKK.png" },
	"KLM": { name: "KLM", image: "KLM.png" },
	//"KNA": { name: "Kunming Airlines", image: "KNA.png" },
	//"KOR": { name: "Air Koryo", image: "KOR.png" },
	"KQA": { name: "Kenya Airways", image: "KQA.png" },
	//"KRP": { name: "Carpatair", image: "KRP.png" },
	//"KZR": { name: "Air Astana", image: "KZR.png" },
	//"LAM": { name: "LAM", image: "LAM.png" },
	"LAN": { name: "LATAM Airlines Group", image: "LAN.png" },
	"LAO": { name: "Lao Airlines", image: "LAO.png" },
	"LAP": { name: "LATAM Airlines Paraguay", image: "LAP.png" },
	//"LBT": { name: "Nouvelair", image: "LBT.png" },
	"LCO": { name: "LATAM Cargo Chile", image: "LCO.png" },
	//"LGL": { name: "Luxair", image: "LGL.png" },
	//"LIA": { name: "LIAT Airlines", image: "LIA.png" },
	"LKE": { name: "Lucky Air", image: "LKE.png" },
	//"LMU": { name: "AlMasria Universal Airlines", image: "LMU.png" },
	"LNE": { name: "LATAM Airlines Ecuador", image: "LNE.png" },
	//"LNK": { name: "Airlink", image: "LNK.png" },
	"LOT": { name: "LOT Polish Airlines", image: "LOT.png" },
	"LPE": { name: "LATAM Airlines Peru", image: "LPE.png" },
	//"LRC": { name: "Avianca Costa Rica", image: "LRC.png" },
	"LTG": { name: "LATAM Cargo Brasil", image: "LTG.png" },
	//"LZB": { name: "Bulgaria Air", image: "LZB.png" },
	//"MAA": { name: "LATAM Cargo Mexico", image: "MAA.png" },
	//"MAI": { name: "Mauritania Airlines International", image: "MAI.png" },
	"MAS": { name: "Malaysia Airlines", image: "MAS.png" },
	"MAU": { name: "Air Mauritius", image: "MAU.png" },
	"MDA": { name: "Mandarin Airlines", image: "MDA.png" },
	//"MDG": { name: "Air Madagascar", image: "MDG.png" },
	//"MEA": { name: "MEA", image: "MEA.png" },
	//"MGL": { name: "MIAT Mongolian Airlines", image: "MGL.png" },
	//"MGX": { name: "Montenegro Airlines", image: "MGX.png" },
	//"MLD": { name: "Air Moldova", image: "MLD.png" },
	"MMA": { name: "Myanmar Airways International", image: "MMA.png" },
	//"MMZ": { name: "EuroAtlantic Airways", image: "MMZ.png" },
	//"MNB": { name: "MNG Airlines", image: "MNB.png" },
	//"MPH": { name: "Martinair Cargo", image: "MPH.png" },
	//"MSA": { name: "Mistral Air", image: "MSA.png" },
	//"MSC": { name: "Air Cairo", image: "MSC.png" },
	"MSR": { name: "Egyptair", image: "MSR.png" },
	"MXD": { name: "Malindo Air", image: "MXD.png" },
	"NCA": { name: "NCA Nippon Cargo Airlines", image: "NCA.png" },
	"NCT": { name: "NokScoot", image: "NCT.png" },
	//"NIA": { name: "Nile Air", image: "NIA.png" },
	"NKS": { name: "Spirit Airlines", image: "NKS.png" },
	//"NMA": { name: "Nesma Airlines", image: "NMA.png" },
	//"NMB": { name: "Air Namibia", image: "NMB.png" },
	//"NOS": { name: "Neos", image: "NOS.png" },
	"NWS": { name: "Nordwind Airlines", image: "NWS.png" },
	//"OAL": { name: "Olympic Air", image: "OAL.png" },
	//"OAS": { name: "Oman Air", image: "OAS.png" },
	//"OHY": { name: "Onur Air", image: "OHY.png" },
	//"OKA": { name: "Okay Airways", image: "OKA.png" },
	//"OLA": { name: "Overland Airways", image: "OLA.png" },
	//"ONE": { name: "Avianca Brasil", image: "ONE.png" },
	"PAL": { name: "Philippine Airlines", image: "PAL.png" },
	"PGA": { name: "PGA-Portugalia Airlines", image: "PGA.png" },
	//"PGT": { name: "Pegasus Airlines", image: "PGT.png" },
	//"PIA": { name: "PIA Pakistan International Airlines", image: "PIA.png" },
	"PIC": { name: "Jetstar Pacific", image: "PIC.png" },
	//"PLM": { name: "Wamos Air", image: "PLM.png" },
	//"PRF": { name: "Precision Air", image: "PRF.png" },
	"QFA": { name: "Qantas", image: "QFA.png" },
	"QTR": { name: "Qatar Airways", image: "QTR.png" },
	//"RAM": { name: "Royal Air Maroc", image: "RAM.png" },
	"RBA": { name: "Royal Brunei", image: "RBA.png" },
	//"REU": { name: "Air Austral", image: "REU.png" },
	"RJA": { name: "Royal Jordanian", image: "RJA.png" },
	//"ROT": { name: "TAROM", image: "ROT.png" },
	//"RPB": { name: "Aero Republica", image: "RPB.png" },
	//"RWD": { name: "RwandAir", image: "RWD.png" },
	"RYR": { name: "Ryanair", image: "RYR.png" },
	//"RZO": { name: "Azores Airlines", image: "RZO.png" },
	"SAA": { name: "South African Airways", image: "SAA.png" },
	"SAS": { name: "SAS", image: "SAS.png" },
	//"SAT": { name: "SATA Air Acores", image: "SAT.png" },
	"SBI": { name: "S7 Airlines", image: "SBI.png" },
	//"SCW": { name: "Braathens Regional Aviation", image: "SCW.png" },
	//"SDM": { name: "Rossiya Airlines", image: "SDM.png" },
	//"SEY": { name: "Air Seychelles", image: "SEY.png" },
	//"SFR": { name: "Safair", image: "SFR.png" },
	//"SGQ": { name: "SaudiGulf Airlines", image: "SGQ.png" },
	"SIA": { name: "Singapore Airlines", image: "SIA.png" },
	//"SKU": { name: "SKY Airline", image: "SKU.png" },
	"SLK": { name: "SilkAir", image: "SLK.png" },
	//"SLM": { name: "Surinam Airways", image: "SLM.png" },
	//"SMR": { name: "Somon Air", image: "SMR.png" },
	//"SOL": { name: "Solomon Airlines", image: "SOL.png" },
	"SVA": { name: "Saudia (Saudi Arabian Airlines)", image: "SVA.png" },
	//"SVR": { name: "Ural Airlines", image: "SVR.png" },
	"SWA": { name: "Southwest Airlines", image: "SWA" },
	"SWR": { name: "SWISS", image: "SWR.png" },
	//"SXS": { name: "SunExpress", image: "SXS.png" },
	//"SYR": { name: "Syrianair", image: "SYR.png" },
	//"TAE": { name: "TAME", image: "TAE.png" },
	"TAI": { name: "TACA", image: "TAI.png" },
	"TAM": { name: "LATAM Airlines Brasil", image: "TAM.png" },
	"TAP": { name: "TAP Portugal", image: "TAP.png" },
	//"TAR": { name: "Tunisair", image: "TAR.png" },
	//"TCV": { name: "TACV Cabo Verde Airlines", image: "TCV.png" },
	"TGW": { name: "Scoot", image: "TGW.png" },
	//"TGZ": { name: "Georgian Airways", image: "TGZ.png" },
	"THA": { name: "Thai Airways International", image: "THA.png" },
	"THD": { name: "Thai Smile", image: "THD.png" },
	//"THT": { name: "Air Tahiti Nui", image: "THT.png" },
	"THY": { name: "Turkish Airlines", image: "THY.png" },
	"TLM": { name: "Thai Lion Air", image: "TLM.png" },
	//"TPC": { name: "Air Caledonie", image: "TPC.png" },
	//"TPU": { name: "Avianca Peru", image: "TPU.png" },
	//"TSC": { name: "Air Transat", image: "TSC.png" },
	"TTW": { name: "Tigerair Taiwan", image: "TTW.png" },
	//"TUI": { name: "TUIfly", image: "TUI.png" },
	"TWB": { name: "T'way Air", image: "TWB.png" },
	"UAE": { name: "Emirates", image: "UAE.png" },
	"UAL": { name: "United Airlines", image: "UAL.png" },
	"UIA": { name: "UNI AIR", image: "UIA.png" },
	"UPS": { name: "UPS Airlines", image: "UPS.png" },
	//"UTA": { name: "UTair", image: "UTA.png" },
	//"UZB": { name: "Uzbekistan Airways", image: "UZB.png" },
	//"VBW": { name: "Air Burkina", image: "VBW.png" },
	"VIR": { name: "Virgin Atlantic", image: "VIR.png" },
	"VJC": { name: "Vietjet", image: "VJC.png" },
	//"VLG": { name: "Vueling", image: "VLG.png" },
	"VNL": { name: "Vanilla Air", image: "VNL.png" },
	//"VOE": { name: "Volotea", image: "VOE.png" },
	"VOI": { name: "Volaris", image: "VOI.png" },
	//"VOZ": { name: "Virgin Australia", image: "VOZ.png" },
	//"VSV": { name: "SCAT Airlines", image: "VSV.png" },
	//"VTA": { name: "Air Tahiti", image: "VTA.png" },
	"VTI": { name: "Vistara", image: "VTI.png" },
	//"WDL": { name: "WDL Aviation", image: "WDL.png" },
	"WHT": { name: "White coloured by you", image: "WHT.png" },
	"WIF": { name: "Wideroe", image: "WIF.png" },
	"WJA": { name: "WestJet", image: "WJA.png" },
	"WOW": { name: "WOW air", image: "WOW.png", },
	"XAX": { name: "AirAsia X", image: "XAX.png" },
	"XLF": { name: "XL Airways", image: "XLF.png" },
	


	// "": { name: "", image: ".png" },
};

function findAirlines(flight) {
	var airline_code = flight.substr(0, 3);

	if (typeof AirlinesDatabase[airline_code] !== 'undefined') {
		return AirlinesDatabase[airline_code];
	}

	return null;
}
